version: 2

jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello World!"
      - run: mkdir -p my_workspace
      - run: echo "Trying out my workspaces" > my_workspace/echo_output
      - persist_to_workspace:
          root: my_workspace
          paths: echo_output
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello world 2"
      - attach_workspace:
        at: my_workspace
      - run: echo "Print out something"

workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
